/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SystemAnalyticsRouteImport } from './routes/system-analytics'
import { Route as ReviewerRouteImport } from './routes/reviewer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiCostsRouteImport } from './routes/ai-costs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as GlossaryIndexRouteImport } from './routes/glossary.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as GlossarySlugRouteImport } from './routes/glossary.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ApiReviewerRouteImport } from './routes/api.reviewer'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as LessonsIsland5IndexRouteImport } from './routes/lessons.island5.index'
import { Route as LessonsIsland4IndexRouteImport } from './routes/lessons.island4.index'
import { Route as LessonsIsland3IndexRouteImport } from './routes/lessons.island3.index'
import { Route as LessonsIsland2IndexRouteImport } from './routes/lessons.island2.index'
import { Route as LessonsIsland1IndexRouteImport } from './routes/lessons.island1.index'
import { Route as ShareAchievementAchievementIdRouteImport } from './routes/share.achievement.$achievementId'
import { Route as LessonsIsland5ModuleRouteImport } from './routes/lessons.island5.$module'
import { Route as LessonsIsland4ModuleRouteImport } from './routes/lessons.island4.$module'
import { Route as LessonsIsland3ModuleRouteImport } from './routes/lessons.island3.$module'
import { Route as LessonsIsland2ModuleRouteImport } from './routes/lessons.island2.$module'
import { Route as LessonsIsland1ModuleRouteImport } from './routes/lessons.island1.$module'
import { Route as ApiAchievementFrameAchievementIdRouteImport } from './routes/api.achievement-frame.$achievementId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAnalyticsRoute = SystemAnalyticsRouteImport.update({
  id: '/system-analytics',
  path: '/system-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerRoute = ReviewerRouteImport.update({
  id: '/reviewer',
  path: '/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCostsRoute = AiCostsRouteImport.update({
  id: '/ai-costs',
  path: '/ai-costs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryIndexRoute = GlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarySlugRoute = GlossarySlugRouteImport.update({
  id: '/glossary/$slug',
  path: '/glossary/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewerRoute = ApiReviewerRouteImport.update({
  id: '/api/reviewer',
  path: '/api/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIsland5IndexRoute = LessonsIsland5IndexRouteImport.update({
  id: '/lessons/island5/',
  path: '/lessons/island5/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIsland4IndexRoute = LessonsIsland4IndexRouteImport.update({
  id: '/lessons/island4/',
  path: '/lessons/island4/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIsland3IndexRoute = LessonsIsland3IndexRouteImport.update({
  id: '/lessons/island3/',
  path: '/lessons/island3/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIsland2IndexRoute = LessonsIsland2IndexRouteImport.update({
  id: '/lessons/island2/',
  path: '/lessons/island2/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIsland1IndexRoute = LessonsIsland1IndexRouteImport.update({
  id: '/lessons/island1/',
  path: '/lessons/island1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareAchievementAchievementIdRoute =
  ShareAchievementAchievementIdRouteImport.update({
    id: '/share/achievement/$achievementId',
    path: '/share/achievement/$achievementId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsIsland5ModuleRoute = LessonsIsland5ModuleRouteImport.update({
  id: '/lessons/island5/$module',
  path: '/lessons/island5/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIsland4ModuleRoute = LessonsIsland4ModuleRouteImport.update({
  id: '/lessons/island4/$module',
  path: '/lessons/island4/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIsland3ModuleRoute = LessonsIsland3ModuleRouteImport.update({
  id: '/lessons/island3/$module',
  path: '/lessons/island3/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIsland2ModuleRoute = LessonsIsland2ModuleRouteImport.update({
  id: '/lessons/island2/$module',
  path: '/lessons/island2/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIsland1ModuleRoute = LessonsIsland1ModuleRouteImport.update({
  id: '/lessons/island1/$module',
  path: '/lessons/island1/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAchievementFrameAchievementIdRoute =
  ApiAchievementFrameAchievementIdRouteImport.update({
    id: '/api/achievement-frame/$achievementId',
    path: '/api/achievement-frame/$achievementId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-costs': typeof AiCostsRoute
  '/analytics': typeof AnalyticsRoute
  '/chat': typeof ChatRoute
  '/presentation': typeof PresentationRoute
  '/privacy': typeof PrivacyRoute
  '/reviewer': typeof ReviewerRoute
  '/system-analytics': typeof SystemAnalyticsRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/reviewer': typeof ApiReviewerRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/api/achievement-frame/$achievementId': typeof ApiAchievementFrameAchievementIdRoute
  '/lessons/island1/$module': typeof LessonsIsland1ModuleRoute
  '/lessons/island2/$module': typeof LessonsIsland2ModuleRoute
  '/lessons/island3/$module': typeof LessonsIsland3ModuleRoute
  '/lessons/island4/$module': typeof LessonsIsland4ModuleRoute
  '/lessons/island5/$module': typeof LessonsIsland5ModuleRoute
  '/share/achievement/$achievementId': typeof ShareAchievementAchievementIdRoute
  '/lessons/island1/': typeof LessonsIsland1IndexRoute
  '/lessons/island2/': typeof LessonsIsland2IndexRoute
  '/lessons/island3/': typeof LessonsIsland3IndexRoute
  '/lessons/island4/': typeof LessonsIsland4IndexRoute
  '/lessons/island5/': typeof LessonsIsland5IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-costs': typeof AiCostsRoute
  '/analytics': typeof AnalyticsRoute
  '/chat': typeof ChatRoute
  '/presentation': typeof PresentationRoute
  '/privacy': typeof PrivacyRoute
  '/reviewer': typeof ReviewerRoute
  '/system-analytics': typeof SystemAnalyticsRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/reviewer': typeof ApiReviewerRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/glossary': typeof GlossaryIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/api/achievement-frame/$achievementId': typeof ApiAchievementFrameAchievementIdRoute
  '/lessons/island1/$module': typeof LessonsIsland1ModuleRoute
  '/lessons/island2/$module': typeof LessonsIsland2ModuleRoute
  '/lessons/island3/$module': typeof LessonsIsland3ModuleRoute
  '/lessons/island4/$module': typeof LessonsIsland4ModuleRoute
  '/lessons/island5/$module': typeof LessonsIsland5ModuleRoute
  '/share/achievement/$achievementId': typeof ShareAchievementAchievementIdRoute
  '/lessons/island1': typeof LessonsIsland1IndexRoute
  '/lessons/island2': typeof LessonsIsland2IndexRoute
  '/lessons/island3': typeof LessonsIsland3IndexRoute
  '/lessons/island4': typeof LessonsIsland4IndexRoute
  '/lessons/island5': typeof LessonsIsland5IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-costs': typeof AiCostsRoute
  '/analytics': typeof AnalyticsRoute
  '/chat': typeof ChatRoute
  '/presentation': typeof PresentationRoute
  '/privacy': typeof PrivacyRoute
  '/reviewer': typeof ReviewerRoute
  '/system-analytics': typeof SystemAnalyticsRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/reviewer': typeof ApiReviewerRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/api/achievement-frame/$achievementId': typeof ApiAchievementFrameAchievementIdRoute
  '/lessons/island1/$module': typeof LessonsIsland1ModuleRoute
  '/lessons/island2/$module': typeof LessonsIsland2ModuleRoute
  '/lessons/island3/$module': typeof LessonsIsland3ModuleRoute
  '/lessons/island4/$module': typeof LessonsIsland4ModuleRoute
  '/lessons/island5/$module': typeof LessonsIsland5ModuleRoute
  '/share/achievement/$achievementId': typeof ShareAchievementAchievementIdRoute
  '/lessons/island1/': typeof LessonsIsland1IndexRoute
  '/lessons/island2/': typeof LessonsIsland2IndexRoute
  '/lessons/island3/': typeof LessonsIsland3IndexRoute
  '/lessons/island4/': typeof LessonsIsland4IndexRoute
  '/lessons/island5/': typeof LessonsIsland5IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-costs'
    | '/analytics'
    | '/chat'
    | '/presentation'
    | '/privacy'
    | '/reviewer'
    | '/system-analytics'
    | '/terms'
    | '/api/chat'
    | '/api/reviewer'
    | '/articles/$slug'
    | '/glossary/$slug'
    | '/articles/'
    | '/glossary/'
    | '/lessons/'
    | '/api/achievement-frame/$achievementId'
    | '/lessons/island1/$module'
    | '/lessons/island2/$module'
    | '/lessons/island3/$module'
    | '/lessons/island4/$module'
    | '/lessons/island5/$module'
    | '/share/achievement/$achievementId'
    | '/lessons/island1/'
    | '/lessons/island2/'
    | '/lessons/island3/'
    | '/lessons/island4/'
    | '/lessons/island5/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-costs'
    | '/analytics'
    | '/chat'
    | '/presentation'
    | '/privacy'
    | '/reviewer'
    | '/system-analytics'
    | '/terms'
    | '/api/chat'
    | '/api/reviewer'
    | '/articles/$slug'
    | '/glossary/$slug'
    | '/articles'
    | '/glossary'
    | '/lessons'
    | '/api/achievement-frame/$achievementId'
    | '/lessons/island1/$module'
    | '/lessons/island2/$module'
    | '/lessons/island3/$module'
    | '/lessons/island4/$module'
    | '/lessons/island5/$module'
    | '/share/achievement/$achievementId'
    | '/lessons/island1'
    | '/lessons/island2'
    | '/lessons/island3'
    | '/lessons/island4'
    | '/lessons/island5'
  id:
    | '__root__'
    | '/'
    | '/ai-costs'
    | '/analytics'
    | '/chat'
    | '/presentation'
    | '/privacy'
    | '/reviewer'
    | '/system-analytics'
    | '/terms'
    | '/api/chat'
    | '/api/reviewer'
    | '/articles/$slug'
    | '/glossary/$slug'
    | '/articles/'
    | '/glossary/'
    | '/lessons/'
    | '/api/achievement-frame/$achievementId'
    | '/lessons/island1/$module'
    | '/lessons/island2/$module'
    | '/lessons/island3/$module'
    | '/lessons/island4/$module'
    | '/lessons/island5/$module'
    | '/share/achievement/$achievementId'
    | '/lessons/island1/'
    | '/lessons/island2/'
    | '/lessons/island3/'
    | '/lessons/island4/'
    | '/lessons/island5/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCostsRoute: typeof AiCostsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ChatRoute: typeof ChatRoute
  PresentationRoute: typeof PresentationRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewerRoute: typeof ReviewerRoute
  SystemAnalyticsRoute: typeof SystemAnalyticsRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiReviewerRoute: typeof ApiReviewerRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  GlossarySlugRoute: typeof GlossarySlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  GlossaryIndexRoute: typeof GlossaryIndexRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  ApiAchievementFrameAchievementIdRoute: typeof ApiAchievementFrameAchievementIdRoute
  LessonsIsland1ModuleRoute: typeof LessonsIsland1ModuleRoute
  LessonsIsland2ModuleRoute: typeof LessonsIsland2ModuleRoute
  LessonsIsland3ModuleRoute: typeof LessonsIsland3ModuleRoute
  LessonsIsland4ModuleRoute: typeof LessonsIsland4ModuleRoute
  LessonsIsland5ModuleRoute: typeof LessonsIsland5ModuleRoute
  ShareAchievementAchievementIdRoute: typeof ShareAchievementAchievementIdRoute
  LessonsIsland1IndexRoute: typeof LessonsIsland1IndexRoute
  LessonsIsland2IndexRoute: typeof LessonsIsland2IndexRoute
  LessonsIsland3IndexRoute: typeof LessonsIsland3IndexRoute
  LessonsIsland4IndexRoute: typeof LessonsIsland4IndexRoute
  LessonsIsland5IndexRoute: typeof LessonsIsland5IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-analytics': {
      id: '/system-analytics'
      path: '/system-analytics'
      fullPath: '/system-analytics'
      preLoaderRoute: typeof SystemAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer': {
      id: '/reviewer'
      path: '/reviewer'
      fullPath: '/reviewer'
      preLoaderRoute: typeof ReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-costs': {
      id: '/ai-costs'
      path: '/ai-costs'
      fullPath: '/ai-costs'
      preLoaderRoute: typeof AiCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/': {
      id: '/glossary/'
      path: '/glossary'
      fullPath: '/glossary/'
      preLoaderRoute: typeof GlossaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/$slug': {
      id: '/glossary/$slug'
      path: '/glossary/$slug'
      fullPath: '/glossary/$slug'
      preLoaderRoute: typeof GlossarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviewer': {
      id: '/api/reviewer'
      path: '/api/reviewer'
      fullPath: '/api/reviewer'
      preLoaderRoute: typeof ApiReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/island5/': {
      id: '/lessons/island5/'
      path: '/lessons/island5'
      fullPath: '/lessons/island5/'
      preLoaderRoute: typeof LessonsIsland5IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/island4/': {
      id: '/lessons/island4/'
      path: '/lessons/island4'
      fullPath: '/lessons/island4/'
      preLoaderRoute: typeof LessonsIsland4IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/island3/': {
      id: '/lessons/island3/'
      path: '/lessons/island3'
      fullPath: '/lessons/island3/'
      preLoaderRoute: typeof LessonsIsland3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/island2/': {
      id: '/lessons/island2/'
      path: '/lessons/island2'
      fullPath: '/lessons/island2/'
      preLoaderRoute: typeof LessonsIsland2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/island1/': {
      id: '/lessons/island1/'
      path: '/lessons/island1'
      fullPath: '/lessons/island1/'
      preLoaderRoute: typeof LessonsIsland1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/achievement/$achievementId': {
      id: '/share/achievement/$achievementId'
      path: '/share/achievement/$achievementId'
      fullPath: '/share/achievement/$achievementId'
      preLoaderRoute: typeof ShareAchievementAchievementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/island5/$module': {
      id: '/lessons/island5/$module'
      path: '/lessons/island5/$module'
      fullPath: '/lessons/island5/$module'
      preLoaderRoute: typeof LessonsIsland5ModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/island4/$module': {
      id: '/lessons/island4/$module'
      path: '/lessons/island4/$module'
      fullPath: '/lessons/island4/$module'
      preLoaderRoute: typeof LessonsIsland4ModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/island3/$module': {
      id: '/lessons/island3/$module'
      path: '/lessons/island3/$module'
      fullPath: '/lessons/island3/$module'
      preLoaderRoute: typeof LessonsIsland3ModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/island2/$module': {
      id: '/lessons/island2/$module'
      path: '/lessons/island2/$module'
      fullPath: '/lessons/island2/$module'
      preLoaderRoute: typeof LessonsIsland2ModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/island1/$module': {
      id: '/lessons/island1/$module'
      path: '/lessons/island1/$module'
      fullPath: '/lessons/island1/$module'
      preLoaderRoute: typeof LessonsIsland1ModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/achievement-frame/$achievementId': {
      id: '/api/achievement-frame/$achievementId'
      path: '/api/achievement-frame/$achievementId'
      fullPath: '/api/achievement-frame/$achievementId'
      preLoaderRoute: typeof ApiAchievementFrameAchievementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCostsRoute: AiCostsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ChatRoute: ChatRoute,
  PresentationRoute: PresentationRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewerRoute: ReviewerRoute,
  SystemAnalyticsRoute: SystemAnalyticsRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiReviewerRoute: ApiReviewerRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  GlossarySlugRoute: GlossarySlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  GlossaryIndexRoute: GlossaryIndexRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  ApiAchievementFrameAchievementIdRoute: ApiAchievementFrameAchievementIdRoute,
  LessonsIsland1ModuleRoute: LessonsIsland1ModuleRoute,
  LessonsIsland2ModuleRoute: LessonsIsland2ModuleRoute,
  LessonsIsland3ModuleRoute: LessonsIsland3ModuleRoute,
  LessonsIsland4ModuleRoute: LessonsIsland4ModuleRoute,
  LessonsIsland5ModuleRoute: LessonsIsland5ModuleRoute,
  ShareAchievementAchievementIdRoute: ShareAchievementAchievementIdRoute,
  LessonsIsland1IndexRoute: LessonsIsland1IndexRoute,
  LessonsIsland2IndexRoute: LessonsIsland2IndexRoute,
  LessonsIsland3IndexRoute: LessonsIsland3IndexRoute,
  LessonsIsland4IndexRoute: LessonsIsland4IndexRoute,
  LessonsIsland5IndexRoute: LessonsIsland5IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
